export const GET_ADDRESSES = "GET_ADDRESSES";
export const ADD_ADDRESS = "ADD_ADDRESS";
export const UPDATE_ADDRESS = "UPDATE_ADDRESS";
export const DELETE_ADDRESS = "DELETE_ADDRESS";
export const SINGLE_ADDRESS = "SINGLE_ADDRESS";