export const CREATE_CANCELLED_REQUEST = "CREATE_CANCELLED_REQUEST";
export const CREATE_CANCELLED_SUCCESS = "CREATE_CANCELLED_SUCCESS";
export const CREATE_CANCELLED_FAIL = "CREATE_CANCELLED_FAIL";

export const CANCELLED_ORDER_REQUEST = "CANCELLED_ORDER_REQUEST";
export const CANCELLED_ORDER_SUCCESS = "CANCELLED_ORDER_SUCCESS";
export const CANCELLED_ORDER_FAIL = "CANCELLED_ORDER_FAIL";
