export const CONVERSATION_LIST_REQUEST = "CONVERSATION_LIST_REQUEST";
export const CONVERSATION_LIST_SUCCESS = "CONVERSATION_LIST_SUCCESS";
export const CONVERSATION_LIST_FAIL = "CONVERSATION_LIST_FAIL";
export const NEW_CONVETION_REQUEST = "NEW_CONVETION_REQUEST";
export const NEW_CONVETION_SUCCESS = "NEW_CONVETION_SUCCESS";
export const NEW_CONVETION_FAIL = "NEW_CONVETION_FAIL";