export const CREATE_DELIVERY_REQUEST = "CREATE_DELIVERY_REQUEST";
export const CREATE_DELIVERY_SUCCESS = "CREATE_DELIVERY_SUCCESS";
export const CREATE_DELIVERY_FAIL = "CREATE_DELIVERY_FAIL";

export const GET_DELIVERY_TRACKING_REQUEST = "GET_DELIVERY_TRACKING_REQUEST";
export const GET_DELIVERY_TRACKING_SUCCESS = "GET_DELIVERY_TRACKING_SUCCESS";
export const GET_DELIVERY_TRACKING_FAIL = "GET_DELIVERY_TRACKING_FAIL";

export const GET_DELIVERY_DRIVER_REQUEST = "GET_DELIVERY_DRIVER_REQUEST";
export const GET_DELIVERY_DRIVER_SUCCESS = "GET_DELIVERY_DRIVER_SUCCESS";
export const GET_DELIVERY_DRIVER_FAIL = "GET_DELIVERY_DRIVER_FAIL";

export const UPDATE_DELIVERY_STATUS_REQUEST = "UPDATE_DELIVERY_STATUS_REQUEST";
export const UPDATE_DELIVERY_STATUS_SUCCESS = "UPDATE_DELIVERY_STATUS_SUCCESS";
export const UPDATE_DELIVERY_STATUS_FAIL = "UPDATE_DELIVERY_STATUS_FAIL";

export const HISTORY_DELIVERY_REQUEST = "HISTORY_DELIVERY_REQUEST";
export const HISTORY_DELIVERY_SUCCESS = "HISTORY_DELIVERY_SUCCESS";
export const HISTORY_DELIVERY_FAIL = "HISTORY_DELIVERY_FAIL";

export const COMPLETED_DELIVERY_REQUEST = "COMPLETED_DELIVERY_REQUEST";
export const COMPLETED_DELIVERY_SUCCESS = "COMPLETED_DELIVERY_SUCCESS";
export const COMPLETED_DELIVERY_FAIL = "COMPLETED_DELIVERY_FAIL";

export const DELIVERY_LIST_REQUEST = "DELIVERY_LIST_REQUEST";
export const DELIVERY_LIST_SUCCESS = "DELIVERY_LIST_SUCCESS";
export const DELIVERY_LIST_FAIL = "DELIVERY_LIST_FAIL";

export const THIS_MONTH_DELIVERY_REQUEST = "THIS_MONTH_DELIVERY_REQUEST";
export const THIS_MONTH_DELIVERY_SUCCESS = "THIS_MONTH_DELIVERY_SUCCESS";
export const THIS_MONTH_DELIVERY_FAIL = "THIS_MONTH_DELIVERY_FAIL";

export const REMOVE_DELIVERY_REQUEST = "REMOVE_DELIVERY_REQUEST";
export const REMOVE_DELIVERY_SUCCESS = "REMOVE_DELIVERY_SUCCESS";
export const REMOVE_DELIVERY_FAIL = "REMOVE_DELIVERY_FAIL";

export const QR_CODE_REQUEST = "QR_CODE_REQUEST";
export const QR_CODE_SUCCESS = "QR_CODE_SUCCESS";
export const QR_CODE_FAIL = "QR_CODE_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";