export const CREATE_DRIVER_REQUEST = "CREATE_DRIVER_REQUEST";
export const CREATE_DRIVER_SUCCESS = "CREATE_DRIVER_SUCCESS";
export const CREATE_DRIVER_FAIL = "CREATE_DRIVER_FAIL";

export const DRIVER_APPROVED_REQUEST = "DRIVER_APPROVED_REQUEST";
export const DRIVER_APPROVED_SUCCESS = "DRIVER_APPROVED_SUCCESS";
export const DRIVER_APPROVED_FAIL = "DRIVER_APPROVED_FAIL";

export const DRIVER_REJECTED_REQUEST = "DRIVER_REJECTED_REQUEST";
export const DRIVER_REJECTED_SUCCESS = "DRIVER_REJECTED_SUCCESS";
export const DRIVER_REJECTED_FAIL = "DRIVER_REJECTED_FAIL";

export const DRIVER_LIST_REQUEST = "DRIVER_LIST_REQUEST";
export const DRIVER_LIST_SUCCESS = "DRIVER_LIST_SUCCESS";
export const DRIVER_LIST_FAIL = "DRIVER_LIST_FAIL";

export const DRIVER_LIST_DISAPPROVED_REQUEST = "DRIVER_LIST_DISAPPROVED_REQUEST";
export const DRIVER_LIST_DISAPPROVED_SUCCESS = "DRIVER_LIST_DISAPPROVED_SUCCESS";
export const DRIVER_LIST_DISAPPROVED_FAIL = "DRIVER_LIST_DISAPPROVED_FAIL";

export const SINGLE_DRIVER_REQUEST = "SINGLE_DRIVER_REQUEST";
export const SINGLE_DRIVER_SUCCESS = "SINGLE_DRIVER_SUCCESS";
export const SINGLE_DRIVER_FAIL = "SINGLE_DRIVER_FAIL";

export const DELETE_DRIVER_REQUEST = "DELETE_DRIVER_REQUEST";
export const DELETE_DRIVER_SUCCESS = "DELETE_DRIVER_SUCCESS";
export const DELETE_DRIVER_FAIL = "DELETE_DRIVER_FAIL";

export const ONLY_APPROVED_DRIVER_REQUEST = "ONLY_APPROVED_DRIVER_REQUEST";
export const ONLY_APPROVED_DRIVER_SUCCESS = "ONLY_APPROVED_DRIVER_SUCCESS";
export const ONLY_APPROVED_DRIVER_FAIL = "ONLY_APPROVED_DRIVER_FAIL";

export const ASSIGN_LOCATION_REQUEST = "ASSIGN_LOCATION_REQUEST";
export const ASSIGN_LOCATION_SUCCESS = "ASSIGN_LOCATION_SUCCESS";
export const ASSIGN_LOCATION_FAIL = "ASSIGN_LOCATION_FAIL";

export const MAX_CAPACITY_REQUEST = "MAX_CAPACITY_REQUEST";
export const MAX_CAPACITY_SUCCESS = "MAX_CAPACITY_SUCCESS";
export const MAX_CAPACITY_FAIL = "MAX_CAPACITY_FAIL";

export const UPDATE_AVAILABILITY_REQUEST = "UPDATE_AVAILABILITY_REQUEST";
export const UPDATE_AVAILABILITY_SUCCESS = "UPDATE_AVAILABILITY_SUCCESS";
export const UPDATE_AVAILABILITY_FAIL = "UPDATE_AVAILABILITY_FAIL";

export const REMOVE_LOCATION_REQUEST = "REMOVE_LOCATION_REQUEST";
export const REMOVE_LOCATION_SUCCESS = "REMOVE_LOCATION_SUCCESS";
export const REMOVE_LOCATION_FAIL = "REMOVE_LOCATION_FAIL";

export const DRIVER_PROFILE_REQUEST = "DRIVER_PROFILE_REQUEST";
export const DRIVER_PROFILE_SUCCESS = "DRIVER_PROFILE_SUCCESS";
export const DRIVER_PROFILE_FAIL = "DRIVER_APPROVED_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";