export const INVENTORY_CREATE_REQUEST = "INVENTORY_CREATE_REQUEST"; 
export const INVENTORY_CREATE_SUCCESS = "INVENTORY_CREATE_SUCCESS";
export const INVENTORY_CREATE_FAIL = "INVENTORY_CREATE_FAIL";

export const INVENTORY_UPDATE_REQUEST = "INVENTORY_UPDATE_REQUEST";
export const INVENTORY_UPDATE_SUCCESS = "INVENTORY_UPDATE_SUCCESS";
export const INVENTORY_UPDATE_FAIL = "INVENTORY_UPDATE_FAIL";

export const INVENTORY_DELETE_REQUEST = "INVENTORY_DELETE_REQUEST";
export const INVENTORY_DELETE_SUCCESS = "INVENTORY_DELETE_SUCCESS";
export const INVENTORY_DELETE_FAIL = "INVENTORY_DELETE_FAIL";

export const INVENTORY_ACTIVE_REQUEST = "INVENTORY_ACTIVE_REQUEST";
export const INVENTORY_ACTIVE_SUCCESS = "INVENTORY_ACTIVE_SUCCESS";
export const INVENTORY_ACTIVE_FAIL = "INVENTORY_ACTIVE_FAIL";

export const SINGLE_INVENTORY_REQUEST = "SINGLE_INVENTORY_REQUEST";
export const SINGLE_INVENTORY_SUCCESS = "SINGLE_INVENTORY_SUCCESS";
export const SINGLE_INVENTORY_FAIL = "SINGLE_INVENTORY_FAIL";

export const INVENTORY_PRODUCTS_REQUEST = "INVENTORY_PRODUCTS_REQUEST";
export const INVENTORY_PRODUCTS_SUCCESS = "INVENTORY_PRODUCTS_SUCCESS";
export const INVENTORY_PRODUCTS_FAIL = "INVENTORY_PRODUCTS_FAIL";

export const INVENTORY_DASHBOARD_REQUEST = "INVENTORY_DASHBOARD_REQUEST";
export const INVENTORY_DASHBOARD_SUCCESS = "INVENTORY_DASHBOARD_SUCCESS";
export const INVENTORY_DASHBOARD_FAIL = "INVENTORY_DASHBOARD_FAIL";