export const MEMBER_LIST_REQUEST = 'MEMBER_LIST_REQUEST';
export const MEMBER_LIST_SUCCESS = 'MEMBER_LIST_SUCCESS';
export const MEMBER_LIST_FAIL = 'MEMBER_LIST_FAIL';

export const MEMBER_DETAILS_REQUEST = 'MEMBER_DETAILS_REQUEST';
export const MEMBER_DETAILS_SUCCESS = 'MEMBER_DETAILS_SUCCESS';
export const MEMBER_DETAILS_FAIL = 'MEMBER_DETAILS_FAIL';

export const MEMBER_APPROVE_REQUEST = 'MEMBER_APPROVE_REQUEST';
export const MEMBER_APPROVE_SUCCESS = 'MEMBER_APPROVE_SUCCESS';
export const MEMBER_APPROVE_FAIL = 'MEMBER_APPROVE_FAIL';

export const MEMBER_REJECT_REQUEST = 'MEMBER_REJECT_REQUEST';
export const MEMBER_REJECT_SUCCESS = 'MEMBER_REJECT_SUCCESS';
export const MEMBER_REJECT_FAIL = 'MEMBER_REJECT_FAIL';

export const MEMBER_CREATE_REQUEST = 'MEMBER_CREATE_REQUEST';
export const MEMBER_CREATE_SUCCESS = 'MEMBER_CREATE_SUCCESS';
export const MEMBER_CREATE_FAIL = 'MEMBER_CREATE_FAIL';

export const MEMBER_ALL_REQUEST = 'MEMBER_ALL_REQUEST';
export const MEMBER_ALL_SUCCESS = 'MEMBER_ALL_SUCCESS';
export const MEMBER_ALL_FAIL = 'MEMBER_ALL_FAIL';

export const MEMBER_INACTIVE_REQUEST = 'MEMBER_INACTIVE_REQUEST';
export const MEMBER_INACTIVE_SUCCESS = 'MEMBER_INACTIVE_SUCCESS';
export const MEMBER_INACTIVE_FAIL = 'MEMBER_INACTIVE_FAIL';

export const MEMBER_REMOVE_REQUEST = 'MEMBER_REMOVE_REQUEST';
export const MEMBER_REMOVE_SUCCESS = 'MEMBER_REMOVE_SUCCESS';
export const MEMBER_REMOVE_FAIL = 'MEMBER_REMOVE_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';

