export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST";
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS";
export const ORDER_CREATE_FAIL = "ORDER_CREATE_FAIL";

export const FETCH_ORDERS_REQUEST = "FETCH_ORDERS_REQUEST";
export const FETCH_ORDERS_SUCCESS = "FETCH_ORDERS_SUCCESS";
export const FETCH_ORDERS_FAILURE = "FETCH_ORDERS_FAILURE";

export const ORDER_UPDATE_STATUS_REQUEST = "ORDER_UPDATE_STATUS_REQUEST";
export const ORDER_UPDATE_STATUS_SUCCESS = "ORDER_UPDATE_STATUS_SUCCESS";
export const ORDER_UPDATE_STATUS_FAIL = "ORDER_UPDATE_STATUS_FAIL";

export const ORDER_DELETE_REQUEST = "ORDER_DELETE_REQUEST";
export const ORDER_DELETE_SUCCESS = "ORDER_DELETE_SUCCESS";
export const ORDER_DELETE_FAIL = "ORDER_DELETE_FAIL";

export const ORDER_COOP_USER_REQUEST = "ORDER_COOP_USER_REQUEST";
export const ORDER_COOP_USER_SUCCESS = "ORDER_COOP_USER_SUCCESS";
export const ORDER_COOP_USER_FAIL = "ORDER_COOP_USER_FAIL";

export const SHIPPED_ORDER_REQUEST = "SHIPPED_ORDER_REQUEST";
export const SHIPPED_ORDER_SUCCESS = "SHIPPED_ORDER_SUCCESS";
export const SHIPPED_ORDER_FAIL = "SHIPPED_ORDER_FAIL";

export const HISTORY_DELIVERY_COOP_REQUEST = "HISTORY_DELIVERY_COOP_REQUEST";
export const HISTORY_DELIVERY_COOP_SUCCESS = "HISTORY_DELIVERY_COOP_SUCCESS";
export const HISTORY_DELIVERY_COOP_FAIL = "HISTORY_DELIVERY_COOP_FAIL";

export const COOP_DASHBOARD_REQUEST = "COOP_DASHBOARD_REQUEST";
export const COOP_DASHBOARD_SUCCESS = "COOP_DASHBOARD_SUCCESS";
export const COOP_DASHBOARD_FAIL = "COOP_DASHBOARD_FAIL";

export const OVERALL_DASHBOARD_REQUEST = "OVERALL_DASHBOARD_REQUEST";
export const OVERALL_DASHBOARD_SUCCESS = "OVERALL_DASHBOARD_SUCCESS";
export const OVERALL_DASHBOARD_FAIL = "OVERALL_DASHBOARD_FAIL";