export const POST_REQUEST = "POST_REQUEST";
export const POST_SUCCESS = "POST_SUCCESS";
export const POST_FAIL = "POST_FAIL";

export const GET_POST_REQUEST = "GET_POST_REQUEST";
export const GET_POST_SUCCESS = "GET_POST_SUCCESS";
export const GET_POST_FAIL = "GET_POST_FAIL";

export const GET_POST_USER_REQUEST = "GET_POST_REQUEST";
export const GET_POST_USER_SUCCESS = "GET_POST_SUCCESS";
export const GET_POST_USER_FAIL = "GET_POST_FAIL";

export const UPDATE_POST_REQUEST = "UPDATE_POST_REQUEST";
export const UPDATE_POST_SUCCESS = "UPDATE_POST_SUCCESS";
export const UPDATE_POST_FAIL = "UPDATE_POST_FAIL";

export const POST_DELETE_REQUEST = 'POST_DELETE_REQUEST';
export const POST_DELETE_SUCCESS = 'POST_DELETE_SUCCESS';
export const POST_DELETE_FAIL = 'POST_DELETE_FAIL';

export const POST_SOFTDELETE_REQUEST = 'POST_SOFTDELETE_REQUEST';
export const POST_SOFTDELETE_SUCCESS = 'POST_SOFTDELETE_SUCCESS';
export const POST_SOFTDELETE_FAIL = 'POST_SOFTDELETE_FAIL';

export const POST_RESTORE_REQUEST = 'POST_RESTORE_REQUEST';
export const POST_RESTORE_SUCCESS = 'POST_RESTORE_SUCCESS';
export const POST_RESTORE_FAIL = 'POST_RESTORE_FAIL';

export const POST_LIKE_REQUEST = "POST_LIKE_REQUEST";
export const POST_LIKE_SUCCESS = "POST_LIKE_SUCCESS";
export const POST_LIKE_FAIL = "POST_LIKE_FAIL";

export const POST_APPROVE_REQUEST = 'POST_APPROVE_REQUEST';
export const POST_APPROVE_SUCCESS = 'POST_APPROVE_SUCCESS';
export const POST_APPROVE_FAILURE = 'POST_APPROVE_FAILURE';

export const POST_DECLINE_REQUEST = 'POST_DECLINE_REQUEST';
export const POST_DECLINE_SUCCESS = 'POST_DECLINE_SUCCESS';
export const POST_DECLINE_FAILURE = 'POST_DECLINE_FAILURE';

export const FETCH_APPROVED_POSTS_REQUEST = 'FETCH_APPROVED_POSTS_REQUEST';
export const FETCH_APPROVED_POSTS_SUCCESS = 'FETCH_APPROVED_POSTS_SUCCESS';
export const FETCH_APPROVED_POSTS_FAIL = 'FETCH_APPROVED_POSTS_FAIL';

export const ADD_COMMENT_REQUEST = "ADD_COMMENT_REQUEST";
export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS";
export const ADD_COMMENT_FAIL = "ADD_COMMENT_FAIL";

export const GET_COMMENTS_REQUEST = "GET_COMMENTS_REQUEST";
export const GET_COMMENTS_SUCCESS = "GET_COMMENTS_SUCCESS";
export const GET_COMMENTS_FAIL = "GET_COMMENTS_FAIL";

export const POST_IMAGE_DELETE_REQUEST = 'POST_IMAGE_DELETE_REQUEST';
export const POST_IMAGE_DELETE_SUCCESS = 'POST_IMAGE_DELETE_SUCCESS';
export const POST_IMAGE_DELETE_FAIL = 'POST_IMAGE_DELETE_FAIL';


export const CLEAR_ERRORS = "CLEAR_ERRORS";