export const ALL_PRODUCT_REQUEST = "ALL_PRODUCT_REQUEST";
export const ALL_PRODUCT_SUCCESS = "ALL_PRODUCT_SUCCESS";
export const ALL_PRODUCT_FAIL = "ALL_PRODUCT_FAIL";

export const ALL_PRODUCT_COOP_REQUEST = "ALL_PRODUCT_COOP_REQUEST";
export const ALL_PRODUCT_COOP_SUCCESS = "ALL_PRODUCT_COOP_SUCCESS";
export const ALL_PRODUCT_COOP_FAIL = "ALL_PRODUCT_COOP_FAIL";

export const SINGLE_COOP_REQUEST = "SINGLE_COOP_REQUEST";
export const SINGLE_COOP_SUCCESS = "SINGLE_COOP_SUCCESS";
export const SINGLE_COOP_FAIL = "SINGLE_COOP_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const CREATE_PRODUCT_REQUEST = "CREATE_PRODUCT_REQUEST";
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS";
export const CREATE_PRODUCT_FAIL = "CREATE_PRODUCT_FAIL";

export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_FAIL = "UPDATE_PRODUCT_FAIL";

export const DELETE_PRODUCT_IMAGE_FAIL = "DELETE_PRODUCT_IMAGE";
export const DELETE_PRODUCT_IMAGE_REQUEST = "DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_IMAGE_SUCCESS = "DELETE_PRODUCT_SUCCESS";

export const SOFTDELETE_PRODUCT_REQUEST = "SOFTDELETE_PRODUCT_REQUEST";
export const SOFTDELETE_PRODUCT_SUCCESS = "SOFTDELETE_PRODUCT_SUCCESS";
export const SOFTDELETE_PRODUCT_FAIL = "SOFTDELETE_PRODUCT_FAIL";

export const RESTORE_PRODUCT_REQUEST = "RESTORE_PRODUCT_REQUEST";
export const RESTORE_PRODUCT_SUCCESS = "RESTORE_PRODUCT_SUCCESS";
export const RESTORE_PRODUCT_FAIL = "RESTORE_PRODUCT_FAIL";

export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAIL = "DELETE_PRODUCT_FAIL";

export const ARCHIVE_PRODUCT_REQUEST = "ARCHIVE_PRODUCT_REQUEST";
export const ARCHIVE_PRODUCT_SUCCESS = "ARCHIVE_PRODUCT_SUCCESS";
export const ARCHIVE_PRODUCT_FAIL = "ARCHIVE_PRODUCT_FAIL";

export const GET_SINGLE_PRODUCT_REQUEST = "GET_SINGLE_PRODUCT_REQUEST";
export const GET_SINGLE_PRODUCT_SUCCESS = "GET_SINGLE_PRODUCT_SUCCESS";
export const GET_SINGLE_PRODUCT_FAIL = "GET_SINGLE_PRODUCT_FAIL";

export const PRODUCT_ACTIVE_REQUEST = "PRODUCT_ACTIVE_REQUEST";
export const PRODUCT_ACTIVE_SUCCESS = "PRODUCT_ACTIVE_SUCCESS";
export const PRODUCT_ACTIVE_FAIL = "PRODUCT_ACTIVE_FAIL";