// Daily Sales
export const GET_DAILY_SALES_REQUEST = 'GET_DAILY_SALES_REQUEST';
export const GET_DAILY_SALES_SUCCESS = 'GET_DAILY_SALES_SUCCESS';
export const GET_DAILY_SALES_FAIL = 'GET_DAILY_SALES_FAIL';

// Weekly Sales
export const GET_WEEKLY_SALES_REQUEST = 'GET_WEEKLY_SALES_REQUEST';
export const GET_WEEKLY_SALES_SUCCESS = 'GET_WEEKLY_SALES_SUCCESS';
export const GET_WEEKLY_SALES_FAIL = 'GET_WEEKLY_SALES_FAIL';

// Monthly Sales
export const GET_MONTHLY_SALES_REQUEST = 'GET_MONTHLY_SALES_REQUEST';
export const GET_MONTHLY_SALES_SUCCESS = 'GET_MONTHLY_SALES_SUCCESS';
export const GET_MONTHLY_SALES_FAIL = 'GET_MONTHLY_SALES_FAIL';

// Common Sales Error (for global errors, if needed)
export const SALES_ERROR = 'SALES_ERROR';
