export const CREATE_TRANSACTION_REQUEST = "CREATE_TRANSACTION_REQUEST";
export const CREATE_TRANSACTION_SUCCESS = "CREATE_TRANSACTION_SUCCESS";
export const CREATE_TRANSACTION_FAIL = "CREATE_TRANSACTION_FAIL";

export const GET_PENDING_TRANSACTIONS_REQUEST = "GET_PENDING_TRANSACTIONS_REQUEST";
export const GET_PENDING_TRANSACTIONS_SUCCESS = "GET_PENDING_TRANSACTIONS_SUCCESS";
export const GET_PENDING_TRANSACTIONS_FAIL = "GET_PENDING_TRANSACTIONS_FAIL";

export const GET_SUCCESS_TRANSACTIONS_REQUEST = "GET_SUCCESS_TRANSACTIONS_REQUEST";
export const GET_SUCCESS_TRANSACTIONS_SUCCESS = "GET_SUCCESS_TRANSACTIONS_SUCCESS";
export const GET_SUCCESS_TRANSACTIONS_FAIL = "GET_SUCCESS_TRANSACTIONS_FAIL";

export const GET_SINGLE_TRANSACTION_REQUEST = "GET_SINGLE_TRANSACTION_REQUEST";
export const GET_SINGLE_TRANSACTION_SUCCESS = "GET_SINGLE_TRANSACTION_SUCCESS";
export const GET_SINGLE_TRANSACTION_FAIL = "GET_SINGLE_TRANSACTION_FAIL";

export const GET_UPDATE_WITHDRAW_REQUEST = "GET_UPDATE_WITHDRAW_REQUEST";
export const GET_UPDATE_WITHDRAW_SUCCESS = "GET_UPDATE_WITHDRAW_SUCCESS";
export const GET_UPDATE_WITHDRAW_FAIL = "GET_UPDATE_WITHDRAW_FAIL";

export const GET_USER_WITHDRAWS_REQUEST = "GET_USER_WITHDRAWS_REQUEST";
export const GET_USER_WITHDRAWS_SUCCESS = "GET_USER_WITHDRAWS_SUCCESS";
export const GET_USER_WITHDRAWS_FAIL = "GET_USER_WITHDRAWS_FAIL";

export const REFUND_PENDING_REQUEST = "REFUND_PENDING_REQUEST";
export const REFUND_PENDING_SUCCESS = "REFUND_PENDING_SUCCESS";
export const REFUND_PENDING_FAIL = "REFUND_PENDING_FAIL";

export const REFUND_SUCCESS_REQUEST = "REFUND_SUCCESS_REQUEST";
export const REFUND_SUCCESS_SUCCESS = "REFUND_SUCCESS_SUCCESS";
export const REFUND_SUCCESS_FAIL = "REFUND_SUCCESS_FAIL";
