export const TYPE_LIST_REQUEST = "TYPE_LIST_REQUEST";
export const TYPE_LIST_SUCCESS = "TYPE_LIST_SUCCESS";
export const TYPE_LIST_FAIL = "TYPE_LIST_FAIL";

export const TYPE_CREATE_REQUEST = "TYPE_CREATE_REQUEST";
export const TYPE_CREATE_SUCCESS = "TYPE_CREATE_SUCCESS";
export const TYPE_CREATE_FAIL = "TYPE_CREATE_FAIL";


export const TYPE_DELETE_REQUEST = "TYPE_DELETE_REQUEST";
export const TYPE_DELETE_SUCCESS = "TYPE_DELETE_SUCCESS";
export const TYPE_DELETE_FAIL = "TYPE_DELETE_FAIL";

export const TYPE_UPDATE_REQUEST = 'TYPE_UPDATE_REQUEST';
export const TYPE_UPDATE_SUCCESS = 'TYPE_UPDATE_SUCCESS';
export const TYPE_UPDATE_FAIL = 'TYPE_UPDATE_FAIL';

export const CLEAR_TYPE_ERRORS = "CLEAR_TYPE_ERRORS";
