export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";

export const OTP_USER_REQUEST = "OTP_USER_REQUEST";
export const OTP_USER_SUCCESS = "OTP_USER_SUCCESS";
export const OTP_USER_FAIL = "OTP_USER_FAIL";

export const USER_PROFILE_REQUEST = "USER_PROFILE_REQUEST";
export const USER_PROFILE_SUCCESS = "USER_PROFILE_SUCCESS";
export const USER_PROFILE_FAIL = "USER_PROFILE_FAIL";

export const EDIT_PROFILE_REQUEST = "EDIT_PROFILE_REQUEST";
export const EDIT_PROFILE_SUCCESS = "EDIT_PROFILE_SUCCESS";
export const EDIT_PROFILE_FAIL = "EDIT_PROFILE_FAIL";

export const WISH_USER_REQUEST = "WISH_USER_REQUEST";
export const WISH_USER_SUCCESS = "WISH_USER_SUCCESS";
export const WISH_USER_FAIL = "WISH_USER_FAIL";

export const USER_MESSAGE_REQUEST = "USER_MESSAGE_REQUEST";
export const USER_MESSAGE_SUCCESS = "USER_MESSAGE_SUCCESS";
export const USER_MESSAGE_FAIL = "USER_MESSAGE_FAIL";

export const WISHLIST_REQUEST = "WISHLIST_REQUEST";
export const WISHLIST_SUCCESS = "WISHLIST_SUCCESS";
export const WISHLIST_FAIL = "WISHLIST_FAIL";

export const GET_ALL_USERS_REQUEST = "GET_ALL_USERS_REQUEST";
export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS";
export const GET_ALL_USERS_FAIL = "GET_ALL_USERS_FAIL";

export const CLEAR_REGISTER = "CLEAR_REGISTER";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const USER_DELETE_REQUEST = "USER_DELETE_REQUEST";
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS";
export const USER_DELETE_FAIL = "USER_DELETE_FAIL";

export const USER_SOFTDELETE_REQUEST = "USER_SOFTDELETE_REQUEST";
export const USER_SOFTDELETE_SUCCESS = "USER_SOFTDELETE_SUCCESS";
export const USER_SOFTDELETE_FAIL = "USER_SOFTDELETE_FAIL";

export const USER_RESTORE_REQUEST = "USER_RESTORE_REQUEST";
export const USER_RESTORE_SUCCESS = "USER_RESTORE_SUCCESS";
export const USER_RESTORE_FAIL = "USER_RESTORE_FAIL";

export const GET_USER_COUNT_REQUEST = "GET_USER_COUNT_REQUEST";
export const GET_USER_COUNT_SUCCESS = "GET_USER_COUNT_SUCCESS";
export const GET_USER_COUNT_FAIL = "GET_USER_COUNT_FAIL";

export const SAVE_USER_DEVICE_TOKEN_REQUEST = "SAVE_USER_DEVICE_TOKEN_REQUEST";
export const SAVE_USER_DEVICE_TOKEN_SUCCESS = "SAVE_USER_DEVICE_TOKEN_SUCCESS";
export const SAVE_USER_DEVICE_TOKEN_FAIL = "SAVE_USER_DEVICE_TOKEN_FAIL";

export const CHECK_EMAIL_REQUEST = "CHECK_EMAIL_REQUEST";
export const CHECK_EMAIL_SUCCESS = "CHECK_EMAIL_SUCCESS";
export const CHECK_EMAIL_FAIL = "CHECK_EMAIL_FAIL";

export const OTP_FORGOT_PASSWORD_REQUEST = "OTP_FORGOT_PASSWORD_REQUEST";
export const OTP_FORGOT_PASSWORD_SUCCESS = "OTP_FORGOT_PASSWORD_SUCCESS";
export const OTP_FORGOT_PASSWORD_FAIL = "OTP_FORGOT_PASSWORD_FAIL";

export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";

export const COUNT_USER_REQUEST = "COUNT_USER_REQUEST";
export const COUNT_USER_SUCCESS = "COUNT_USER_SUCCESS";
export const COUNT_USER_FAIL = "COUNT_USER_FAIL";

export const GOOGLE_LOGIN_WEB_REQUEST = "GOOGLE_LOGIN_WEB_REQUEST";
export const GOOGLE_LOGIN_WEB_SUCCESS = "GOOGLE_LOGIN_WEB_SUCCESS";
export const GOOGLE_LOGIN_WEB_FAIL = "GOOGLE_LOGIN_WEB_FAIL";
